# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 543)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(865, 543))
        MainWindow.setMaximumSize(QtCore.QSize(865, 543))
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        font.setPointSize(17)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.SaudiArabia))
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(11, 10, 841, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(841, 461))
        self.tabWidget.setMaximumSize(QtCore.QSize(841, 461))
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(12, 10, 812, 398))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setToolTipDuration(-1)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_deleteData = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_deleteData.setGeometry(QtCore.QRect(298, 352, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_deleteData.sizePolicy().hasHeightForWidth())
        self.pushButton_deleteData.setSizePolicy(sizePolicy)
        self.pushButton_deleteData.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_deleteData.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_deleteData.setFont(font)
        self.pushButton_deleteData.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imgs/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_deleteData.setIcon(icon1)
        self.pushButton_deleteData.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_deleteData.setAutoDefault(False)
        self.pushButton_deleteData.setObjectName("pushButton_deleteData")
        self.lineEdit_Whats = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Whats.setGeometry(QtCore.QRect(522, 258, 195, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Whats.sizePolicy().hasHeightForWidth())
        self.lineEdit_Whats.setSizePolicy(sizePolicy)
        self.lineEdit_Whats.setMinimumSize(QtCore.QSize(195, 32))
        self.lineEdit_Whats.setMaximumSize(QtCore.QSize(195, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_Whats.setFont(font)
        self.lineEdit_Whats.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Whats.setObjectName("lineEdit_Whats")
        self.lineEdit_StudID = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_StudID.setGeometry(QtCore.QRect(522, 106, 195, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_StudID.sizePolicy().hasHeightForWidth())
        self.lineEdit_StudID.setSizePolicy(sizePolicy)
        self.lineEdit_StudID.setMinimumSize(QtCore.QSize(195, 32))
        self.lineEdit_StudID.setMaximumSize(QtCore.QSize(195, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_StudID.setFont(font)
        self.lineEdit_StudID.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_StudID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_StudID.setPlaceholderText("")
        self.lineEdit_StudID.setObjectName("lineEdit_StudID")
        self.label_Faculty = QtWidgets.QLabel(self.groupBox)
        self.label_Faculty.setGeometry(QtCore.QRect(720, 144, 80, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Faculty.sizePolicy().hasHeightForWidth())
        self.label_Faculty.setSizePolicy(sizePolicy)
        self.label_Faculty.setMinimumSize(QtCore.QSize(80, 32))
        self.label_Faculty.setMaximumSize(QtCore.QSize(80, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_Faculty.setFont(font)
        self.label_Faculty.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Faculty.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Faculty.setObjectName("label_Faculty")
        self.pushButton_updateData = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_updateData.setGeometry(QtCore.QRect(384, 352, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_updateData.sizePolicy().hasHeightForWidth())
        self.pushButton_updateData.setSizePolicy(sizePolicy)
        self.pushButton_updateData.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_updateData.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_updateData.setFont(font)
        self.pushButton_updateData.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imgs/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_updateData.setIcon(icon2)
        self.pushButton_updateData.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_updateData.setObjectName("pushButton_updateData")
        self.lineEdit_Mobile = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Mobile.setGeometry(QtCore.QRect(522, 220, 195, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Mobile.sizePolicy().hasHeightForWidth())
        self.lineEdit_Mobile.setSizePolicy(sizePolicy)
        self.lineEdit_Mobile.setMinimumSize(QtCore.QSize(195, 32))
        self.lineEdit_Mobile.setMaximumSize(QtCore.QSize(195, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_Mobile.setFont(font)
        self.lineEdit_Mobile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Mobile.setObjectName("lineEdit_Mobile")
        self.lineEdit_Faculty = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Faculty.setGeometry(QtCore.QRect(522, 144, 195, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Faculty.sizePolicy().hasHeightForWidth())
        self.lineEdit_Faculty.setSizePolicy(sizePolicy)
        self.lineEdit_Faculty.setMinimumSize(QtCore.QSize(195, 32))
        self.lineEdit_Faculty.setMaximumSize(QtCore.QSize(195, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_Faculty.setFont(font)
        self.lineEdit_Faculty.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_Faculty.setObjectName("lineEdit_Faculty")
        self.pushButton_cleanData = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_cleanData.setGeometry(QtCore.QRect(639, 352, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cleanData.sizePolicy().hasHeightForWidth())
        self.pushButton_cleanData.setSizePolicy(sizePolicy)
        self.pushButton_cleanData.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_cleanData.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_cleanData.setFont(font)
        self.pushButton_cleanData.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imgs/clean.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cleanData.setIcon(icon3)
        self.pushButton_cleanData.setIconSize(QtCore.QSize(34, 34))
        self.pushButton_cleanData.setObjectName("pushButton_cleanData")
        self.pushButton_searchData = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_searchData.setGeometry(QtCore.QRect(469, 352, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_searchData.sizePolicy().hasHeightForWidth())
        self.pushButton_searchData.setSizePolicy(sizePolicy)
        self.pushButton_searchData.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_searchData.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_searchData.setFont(font)
        self.pushButton_searchData.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("imgs/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_searchData.setIcon(icon4)
        self.pushButton_searchData.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_searchData.setObjectName("pushButton_searchData")
        self.lineEdit_Address = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Address.setGeometry(QtCore.QRect(522, 182, 195, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Address.sizePolicy().hasHeightForWidth())
        self.lineEdit_Address.setSizePolicy(sizePolicy)
        self.lineEdit_Address.setMinimumSize(QtCore.QSize(195, 32))
        self.lineEdit_Address.setMaximumSize(QtCore.QSize(195, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_Address.setFont(font)
        self.lineEdit_Address.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Address.setObjectName("lineEdit_Address")
        self.label_StudID = QtWidgets.QLabel(self.groupBox)
        self.label_StudID.setGeometry(QtCore.QRect(720, 106, 80, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_StudID.sizePolicy().hasHeightForWidth())
        self.label_StudID.setSizePolicy(sizePolicy)
        self.label_StudID.setMinimumSize(QtCore.QSize(80, 32))
        self.label_StudID.setMaximumSize(QtCore.QSize(80, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_StudID.setFont(font)
        self.label_StudID.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_StudID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_StudID.setObjectName("label_StudID")
        self.lineEdit_FName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_FName.setGeometry(QtCore.QRect(522, 30, 195, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_FName.sizePolicy().hasHeightForWidth())
        self.lineEdit_FName.setSizePolicy(sizePolicy)
        self.lineEdit_FName.setMinimumSize(QtCore.QSize(195, 32))
        self.lineEdit_FName.setMaximumSize(QtCore.QSize(195, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_FName.setFont(font)
        self.lineEdit_FName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_FName.setPlaceholderText("")
        self.lineEdit_FName.setObjectName("lineEdit_FName")
        self.lineEdit_Nationality = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Nationality.setGeometry(QtCore.QRect(522, 68, 195, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Nationality.sizePolicy().hasHeightForWidth())
        self.lineEdit_Nationality.setSizePolicy(sizePolicy)
        self.lineEdit_Nationality.setMinimumSize(QtCore.QSize(195, 32))
        self.lineEdit_Nationality.setMaximumSize(QtCore.QSize(195, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_Nationality.setFont(font)
        self.lineEdit_Nationality.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_Nationality.setPlaceholderText("")
        self.lineEdit_Nationality.setObjectName("lineEdit_Nationality")
        self.pushButton_addData = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_addData.setGeometry(QtCore.QRect(724, 352, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_addData.sizePolicy().hasHeightForWidth())
        self.pushButton_addData.setSizePolicy(sizePolicy)
        self.pushButton_addData.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_addData.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_addData.setFont(font)
        self.pushButton_addData.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("imgs/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_addData.setIcon(icon5)
        self.pushButton_addData.setIconSize(QtCore.QSize(27, 26))
        self.pushButton_addData.setObjectName("pushButton_addData")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(12, 30, 500, 298))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(500, 298))
        self.tableWidget.setMaximumSize(QtCore.QSize(500, 298))
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        font.setPointSize(17)
        self.tableWidget.setFont(font)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.label_Disability = QtWidgets.QLabel(self.groupBox)
        self.label_Disability.setGeometry(QtCore.QRect(720, 296, 80, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Disability.sizePolicy().hasHeightForWidth())
        self.label_Disability.setSizePolicy(sizePolicy)
        self.label_Disability.setMinimumSize(QtCore.QSize(80, 32))
        self.label_Disability.setMaximumSize(QtCore.QSize(80, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_Disability.setFont(font)
        self.label_Disability.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Disability.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Disability.setObjectName("label_Disability")
        self.label_Whats = QtWidgets.QLabel(self.groupBox)
        self.label_Whats.setGeometry(QtCore.QRect(720, 258, 80, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Whats.sizePolicy().hasHeightForWidth())
        self.label_Whats.setSizePolicy(sizePolicy)
        self.label_Whats.setMinimumSize(QtCore.QSize(80, 32))
        self.label_Whats.setMaximumSize(QtCore.QSize(80, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_Whats.setFont(font)
        self.label_Whats.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Whats.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Whats.setObjectName("label_Whats")
        self.lineEdit_Disability = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Disability.setGeometry(QtCore.QRect(522, 296, 195, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Disability.sizePolicy().hasHeightForWidth())
        self.lineEdit_Disability.setSizePolicy(sizePolicy)
        self.lineEdit_Disability.setMinimumSize(QtCore.QSize(195, 32))
        self.lineEdit_Disability.setMaximumSize(QtCore.QSize(195, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_Disability.setFont(font)
        self.lineEdit_Disability.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_Disability.setObjectName("lineEdit_Disability")
        self.label_Address = QtWidgets.QLabel(self.groupBox)
        self.label_Address.setGeometry(QtCore.QRect(720, 182, 80, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Address.sizePolicy().hasHeightForWidth())
        self.label_Address.setSizePolicy(sizePolicy)
        self.label_Address.setMinimumSize(QtCore.QSize(80, 32))
        self.label_Address.setMaximumSize(QtCore.QSize(80, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_Address.setFont(font)
        self.label_Address.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Address.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Address.setObjectName("label_Address")
        self.label_Nationality = QtWidgets.QLabel(self.groupBox)
        self.label_Nationality.setGeometry(QtCore.QRect(720, 68, 80, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Nationality.sizePolicy().hasHeightForWidth())
        self.label_Nationality.setSizePolicy(sizePolicy)
        self.label_Nationality.setMinimumSize(QtCore.QSize(80, 32))
        self.label_Nationality.setMaximumSize(QtCore.QSize(80, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_Nationality.setFont(font)
        self.label_Nationality.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Nationality.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Nationality.setObjectName("label_Nationality")
        self.pushButton_displayData = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_displayData.setGeometry(QtCore.QRect(554, 352, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_displayData.sizePolicy().hasHeightForWidth())
        self.pushButton_displayData.setSizePolicy(sizePolicy)
        self.pushButton_displayData.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_displayData.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_displayData.setFont(font)
        self.pushButton_displayData.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("imgs/report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_displayData.setIcon(icon6)
        self.pushButton_displayData.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_displayData.setObjectName("pushButton_displayData")
        self.label_Mobile = QtWidgets.QLabel(self.groupBox)
        self.label_Mobile.setGeometry(QtCore.QRect(720, 220, 80, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Mobile.sizePolicy().hasHeightForWidth())
        self.label_Mobile.setSizePolicy(sizePolicy)
        self.label_Mobile.setMinimumSize(QtCore.QSize(80, 32))
        self.label_Mobile.setMaximumSize(QtCore.QSize(80, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_Mobile.setFont(font)
        self.label_Mobile.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Mobile.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Mobile.setObjectName("label_Mobile")
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(1, 334, 810, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setMinimumSize(QtCore.QSize(810, 15))
        self.line_3.setMaximumSize(QtCore.QSize(810, 15))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_folder_stud = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_folder_stud.setGeometry(QtCore.QRect(212, 352, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_folder_stud.sizePolicy().hasHeightForWidth())
        self.pushButton_folder_stud.setSizePolicy(sizePolicy)
        self.pushButton_folder_stud.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_folder_stud.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_folder_stud.setFont(font)
        self.pushButton_folder_stud.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("imgs/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_folder_stud.setIcon(icon7)
        self.pushButton_folder_stud.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_folder_stud.setObjectName("pushButton_folder_stud")
        self.pushButton_manual_tab1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_manual_tab1.setGeometry(QtCore.QRect(14, 352, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_manual_tab1.sizePolicy().hasHeightForWidth())
        self.pushButton_manual_tab1.setSizePolicy(sizePolicy)
        self.pushButton_manual_tab1.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_manual_tab1.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_manual_tab1.setFont(font)
        self.pushButton_manual_tab1.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("imgs/instructions.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_manual_tab1.setIcon(icon8)
        self.pushButton_manual_tab1.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_manual_tab1.setObjectName("pushButton_manual_tab1")
        self.label_FName_2 = QtWidgets.QLabel(self.groupBox)
        self.label_FName_2.setGeometry(QtCore.QRect(720, 30, 80, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_FName_2.sizePolicy().hasHeightForWidth())
        self.label_FName_2.setSizePolicy(sizePolicy)
        self.label_FName_2.setMinimumSize(QtCore.QSize(80, 32))
        self.label_FName_2.setMaximumSize(QtCore.QSize(80, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_FName_2.setFont(font)
        self.label_FName_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_FName_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_FName_2.setObjectName("label_FName_2")
        self.pushButton_copy = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_copy.setGeometry(QtCore.QRect(126, 352, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_copy.sizePolicy().hasHeightForWidth())
        self.pushButton_copy.setSizePolicy(sizePolicy)
        self.pushButton_copy.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_copy.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_copy.setFont(font)
        self.pushButton_copy.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("imgs/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_copy.setIcon(icon9)
        self.pushButton_copy.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_copy.setObjectName("pushButton_copy")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(120, 8, 610, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(610, 400))
        self.groupBox_2.setMaximumSize(QtCore.QSize(610, 400))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(11, 30, 180, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(180, 32))
        self.comboBox.setMaximumSize(QtCore.QSize(180, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.textEdit_need = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_need.setGeometry(QtCore.QRect(98, 120, 500, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_need.sizePolicy().hasHeightForWidth())
        self.textEdit_need.setSizePolicy(sizePolicy)
        self.textEdit_need.setMinimumSize(QtCore.QSize(500, 180))
        self.textEdit_need.setMaximumSize(QtCore.QSize(500, 180))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.textEdit_need.setFont(font)
        self.textEdit_need.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_need.setToolTip("")
        self.textEdit_need.setWhatsThis("")
        self.textEdit_need.setObjectName("textEdit_need")
        self.pushButton_saveReport = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_saveReport.setGeometry(QtCore.QRect(139, 336, 110, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_saveReport.sizePolicy().hasHeightForWidth())
        self.pushButton_saveReport.setSizePolicy(sizePolicy)
        self.pushButton_saveReport.setMinimumSize(QtCore.QSize(110, 32))
        self.pushButton_saveReport.setMaximumSize(QtCore.QSize(110, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_saveReport.setFont(font)
        self.pushButton_saveReport.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("imgs/draw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_saveReport.setIcon(icon10)
        self.pushButton_saveReport.setIconSize(QtCore.QSize(28, 28))
        self.pushButton_saveReport.setObjectName("pushButton_saveReport")
        self.pushButton_updateComboBox = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_updateComboBox.setGeometry(QtCore.QRect(290, 30, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_updateComboBox.sizePolicy().hasHeightForWidth())
        self.pushButton_updateComboBox.setSizePolicy(sizePolicy)
        self.pushButton_updateComboBox.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_updateComboBox.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_updateComboBox.setFont(font)
        self.pushButton_updateComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_updateComboBox.setIcon(icon2)
        self.pushButton_updateComboBox.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_updateComboBox.setObjectName("pushButton_updateComboBox")
        self.pushButton_saveVisit = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_saveVisit.setGeometry(QtCore.QRect(12, 120, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_saveVisit.sizePolicy().hasHeightForWidth())
        self.pushButton_saveVisit.setSizePolicy(sizePolicy)
        self.pushButton_saveVisit.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_saveVisit.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_saveVisit.setFont(font)
        self.pushButton_saveVisit.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("imgs/save-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_saveVisit.setIcon(icon11)
        self.pushButton_saveVisit.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_saveVisit.setObjectName("pushButton_saveVisit")
        self.label_chooceStud = QtWidgets.QLabel(self.groupBox_2)
        self.label_chooceStud.setGeometry(QtCore.QRect(200, 30, 80, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_chooceStud.sizePolicy().hasHeightForWidth())
        self.label_chooceStud.setSizePolicy(sizePolicy)
        self.label_chooceStud.setMinimumSize(QtCore.QSize(80, 32))
        self.label_chooceStud.setMaximumSize(QtCore.QSize(800, 800))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_chooceStud.setFont(font)
        self.label_chooceStud.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_chooceStud.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_chooceStud.setObjectName("label_chooceStud")
        self.label_descriptionChoice = QtWidgets.QLabel(self.groupBox_2)
        self.label_descriptionChoice.setEnabled(True)
        self.label_descriptionChoice.setGeometry(QtCore.QRect(150, 63, 450, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_descriptionChoice.sizePolicy().hasHeightForWidth())
        self.label_descriptionChoice.setSizePolicy(sizePolicy)
        self.label_descriptionChoice.setMinimumSize(QtCore.QSize(450, 20))
        self.label_descriptionChoice.setMaximumSize(QtCore.QSize(450, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_descriptionChoice.setFont(font)
        self.label_descriptionChoice.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_descriptionChoice.setTextFormat(QtCore.Qt.AutoText)
        self.label_descriptionChoice.setScaledContents(False)
        self.label_descriptionChoice.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_descriptionChoice.setObjectName("label_descriptionChoice")
        self.label_resultVisit = QtWidgets.QLabel(self.groupBox_2)
        self.label_resultVisit.setGeometry(QtCore.QRect(478, 88, 120, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_resultVisit.sizePolicy().hasHeightForWidth())
        self.label_resultVisit.setSizePolicy(sizePolicy)
        self.label_resultVisit.setMinimumSize(QtCore.QSize(120, 32))
        self.label_resultVisit.setMaximumSize(QtCore.QSize(120, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_resultVisit.setFont(font)
        self.label_resultVisit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_resultVisit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_resultVisit.setObjectName("label_resultVisit")
        self.label_descriptionResult = QtWidgets.QLabel(self.groupBox_2)
        self.label_descriptionResult.setGeometry(QtCore.QRect(28, 301, 570, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_descriptionResult.sizePolicy().hasHeightForWidth())
        self.label_descriptionResult.setSizePolicy(sizePolicy)
        self.label_descriptionResult.setMinimumSize(QtCore.QSize(570, 20))
        self.label_descriptionResult.setMaximumSize(QtCore.QSize(570, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_descriptionResult.setFont(font)
        self.label_descriptionResult.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_descriptionResult.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_descriptionResult.setObjectName("label_descriptionResult")
        self.label_dateVisitReport = QtWidgets.QLabel(self.groupBox_2)
        self.label_dateVisitReport.setGeometry(QtCore.QRect(478, 336, 120, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dateVisitReport.sizePolicy().hasHeightForWidth())
        self.label_dateVisitReport.setSizePolicy(sizePolicy)
        self.label_dateVisitReport.setMinimumSize(QtCore.QSize(120, 32))
        self.label_dateVisitReport.setMaximumSize(QtCore.QSize(120, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_dateVisitReport.setFont(font)
        self.label_dateVisitReport.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_dateVisitReport.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_dateVisitReport.setObjectName("label_dateVisitReport")
        self.label_descriptionReport = QtWidgets.QLabel(self.groupBox_2)
        self.label_descriptionReport.setGeometry(QtCore.QRect(238, 369, 360, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_descriptionReport.sizePolicy().hasHeightForWidth())
        self.label_descriptionReport.setSizePolicy(sizePolicy)
        self.label_descriptionReport.setMinimumSize(QtCore.QSize(360, 20))
        self.label_descriptionReport.setMaximumSize(QtCore.QSize(360, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_descriptionReport.setFont(font)
        self.label_descriptionReport.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_descriptionReport.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_descriptionReport.setObjectName("label_descriptionReport")
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(1, 318, 608, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(608, 15))
        self.line.setMaximumSize(QtCore.QSize(608, 15))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(1, 80, 608, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(608, 15))
        self.line_2.setMaximumSize(QtCore.QSize(608, 15))
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_2)
        self.dateEdit.setGeometry(QtCore.QRect(260, 336, 217, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMinimumSize(QtCore.QSize(217, 32))
        self.dateEdit.setMaximumSize(QtCore.QSize(217, 32))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        self.dateEdit.setFont(font)
        self.dateEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dateEdit.setWrapping(False)
        self.dateEdit.setFrame(True)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit.setAccelerated(False)
        self.dateEdit.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dateEdit.setProperty("showGroupSeparator", False)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setCurrentSectionIndex(2)
        self.dateEdit.setDate(QtCore.QDate(2020, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.radioButton_attendance = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_attendance.setGeometry(QtCore.QRect(343, 88, 100, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_attendance.sizePolicy().hasHeightForWidth())
        self.radioButton_attendance.setSizePolicy(sizePolicy)
        self.radioButton_attendance.setMinimumSize(QtCore.QSize(100, 32))
        self.radioButton_attendance.setMaximumSize(QtCore.QSize(100, 32))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_attendance.setFont(font)
        self.radioButton_attendance.setObjectName("radioButton_attendance")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_attendance)
        self.radioButton_notNead = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_notNead.setGeometry(QtCore.QRect(80, 88, 220, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_notNead.sizePolicy().hasHeightForWidth())
        self.radioButton_notNead.setSizePolicy(sizePolicy)
        self.radioButton_notNead.setMinimumSize(QtCore.QSize(220, 32))
        self.radioButton_notNead.setMaximumSize(QtCore.QSize(220, 32))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_notNead.setFont(font)
        self.radioButton_notNead.setObjectName("radioButton_notNead")
        self.buttonGroup.addButton(self.radioButton_notNead)
        self.lineEdit_unit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_unit.setGeometry(QtCore.QRect(445, 30, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_unit.sizePolicy().hasHeightForWidth())
        self.lineEdit_unit.setSizePolicy(sizePolicy)
        self.lineEdit_unit.setObjectName("lineEdit_unit")
        self.label_chooceUnit = QtWidgets.QLabel(self.groupBox_2)
        self.label_chooceUnit.setGeometry(QtCore.QRect(490, 30, 110, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_chooceUnit.sizePolicy().hasHeightForWidth())
        self.label_chooceUnit.setSizePolicy(sizePolicy)
        self.label_chooceUnit.setMinimumSize(QtCore.QSize(110, 32))
        self.label_chooceUnit.setMaximumSize(QtCore.QSize(110, 32))
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_chooceUnit.setFont(font)
        self.label_chooceUnit.setObjectName("label_chooceUnit")
        self.pushButton_folder_request = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_folder_request.setGeometry(QtCore.QRect(12, 161, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_folder_request.sizePolicy().hasHeightForWidth())
        self.pushButton_folder_request.setSizePolicy(sizePolicy)
        self.pushButton_folder_request.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_folder_request.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_folder_request.setFont(font)
        self.pushButton_folder_request.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_folder_request.setIcon(icon7)
        self.pushButton_folder_request.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_folder_request.setObjectName("pushButton_folder_request")
        self.pushButton_folder_visit = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_folder_visit.setGeometry(QtCore.QRect(52, 336, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_folder_visit.sizePolicy().hasHeightForWidth())
        self.pushButton_folder_visit.setSizePolicy(sizePolicy)
        self.pushButton_folder_visit.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_folder_visit.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_folder_visit.setFont(font)
        self.pushButton_folder_visit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_folder_visit.setIcon(icon7)
        self.pushButton_folder_visit.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_folder_visit.setObjectName("pushButton_folder_visit")
        self.pushButton_add_names_firebase = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_add_names_firebase.setGeometry(QtCore.QRect(410, 30, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_names_firebase.sizePolicy().hasHeightForWidth())
        self.pushButton_add_names_firebase.setSizePolicy(sizePolicy)
        self.pushButton_add_names_firebase.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_add_names_firebase.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("KacstBook")
        self.pushButton_add_names_firebase.setFont(font)
        self.pushButton_add_names_firebase.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_add_names_firebase.setStyleSheet("")
        self.pushButton_add_names_firebase.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("imgs/app-development.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add_names_firebase.setIcon(icon12)
        self.pushButton_add_names_firebase.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_add_names_firebase.setObjectName("pushButton_add_names_firebase")
        self.pushButton_download_result_firebase = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_download_result_firebase.setGeometry(QtCore.QRect(374, 30, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_download_result_firebase.sizePolicy().hasHeightForWidth())
        self.pushButton_download_result_firebase.setSizePolicy(sizePolicy)
        self.pushButton_download_result_firebase.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_download_result_firebase.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_download_result_firebase.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_download_result_firebase.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("imgs/cloud-computing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_download_result_firebase.setIcon(icon13)
        self.pushButton_download_result_firebase.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_download_result_firebase.setObjectName("pushButton_download_result_firebase")
        self.pushButton_manual_tab2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_manual_tab2.setGeometry(QtCore.QRect(22, 376, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_manual_tab2.sizePolicy().hasHeightForWidth())
        self.pushButton_manual_tab2.setSizePolicy(sizePolicy)
        self.pushButton_manual_tab2.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_manual_tab2.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_manual_tab2.setFont(font)
        self.pushButton_manual_tab2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_manual_tab2.setIcon(icon8)
        self.pushButton_manual_tab2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_manual_tab2.setObjectName("pushButton_manual_tab2")
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(11, 480, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_quit.sizePolicy().hasHeightForWidth())
        self.pushButton_quit.setSizePolicy(sizePolicy)
        self.pushButton_quit.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_quit.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_quit.setFont(font)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("imgs/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_quit.setIcon(icon14)
        self.pushButton_quit.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.pushButton_manual = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_manual.setGeometry(QtCore.QRect(96, 480, 75, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_manual.sizePolicy().hasHeightForWidth())
        self.pushButton_manual.setSizePolicy(sizePolicy)
        self.pushButton_manual.setMinimumSize(QtCore.QSize(75, 32))
        self.pushButton_manual.setMaximumSize(QtCore.QSize(75, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_manual.setFont(font)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("imgs/instruction.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_manual.setIcon(icon15)
        self.pushButton_manual.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_manual.setObjectName("pushButton_manual")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # ===============
        import datetime
        from PyQt5.QtCore import QRegExp
        from PyQt5.QtGui import QRegExpValidator
        self.dateEdit.setDate(datetime.date.today())

        number = QRegExp("[0-9]+")
        validator_number = QRegExpValidator(number)
        address = QRegExp("[0-9/]+")
        validator_address = QRegExpValidator(address)
        letter = QRegExp("[\u0621-\u064A ]+")
        validator_letter = QRegExpValidator(letter)

        self.lineEdit_FName.setValidator(validator_letter)
        self.lineEdit_Nationality.setValidator(validator_letter)
        self.lineEdit_StudID.setValidator(validator_number)
        self.lineEdit_Faculty.setValidator(validator_letter)
        self.lineEdit_Address.setValidator(validator_address)
        self.lineEdit_Mobile.setValidator(validator_number)
        self.lineEdit_Whats.setValidator(validator_number)
        self.lineEdit_Disability.setValidator(validator_letter)
        self.lineEdit_unit.setValidator(validator_number)
        # ====================

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "      MUNASSIQ"))
        MainWindow.setStatusTip(_translate("MainWindow", "أهلا و سهلا في نظام منسق"))
        self.groupBox.setTitle(_translate("MainWindow", "   التسجيل و البيانات   "))
        self.pushButton_deleteData.setStatusTip(_translate("MainWindow", "حذف الطالب من قائمة البيانات"))
        self.pushButton_deleteData.setText(_translate("MainWindow", "حذف"))
        self.lineEdit_Whats.setStatusTip(_translate("MainWindow", "رقم واتس آب. بالأرقام فقط. ـ\\في حال عدم الواتس لا تترك الخانة فاضيية. يرجى كتابة صفر(0)/ـ"))
        self.lineEdit_StudID.setStatusTip(_translate("MainWindow", "        رقم الطالب. بالأرقام فقط"))
        self.label_Faculty.setText(_translate("MainWindow", "جهة التعليم:"))
        self.pushButton_updateData.setStatusTip(_translate("MainWindow", "تحديث بيانات الطالب"))
        self.pushButton_updateData.setText(_translate("MainWindow", "تحديث"))
        self.lineEdit_Mobile.setStatusTip(_translate("MainWindow", "      رقم الجوال. بالأرقام فقط"))
        self.lineEdit_Faculty.setStatusTip(_translate("MainWindow", "        اسم الكلية أو المعهد. بالحروف العربية فقط.        مثلا: الشريعة أو معهد اللغة"))
        self.pushButton_cleanData.setStatusTip(_translate("MainWindow", "مسح الخانات"))
        self.pushButton_cleanData.setWhatsThis(_translate("MainWindow", "кнопка 2"))
        self.pushButton_cleanData.setText(_translate("MainWindow", "مسح"))
        self.pushButton_searchData.setStatusTip(_translate("MainWindow", "بحث في قائمة البيانات"))
        self.pushButton_searchData.setText(_translate("MainWindow", "بحث"))
        self.lineEdit_Address.setStatusTip(_translate("MainWindow", "السكن. بلأرقام و الخط المائل (سلاش). مثلا: 09/106. ـ\\عند البحث يكتب رقم الوحدة فقط. مثلا: 09/ـ"))
        self.label_StudID.setText(_translate("MainWindow", "رقم الطالب:"))
        self.lineEdit_FName.setStatusTip(_translate("MainWindow", "        الاسم كامل. بالحروف العربية فقط.        مثلا: أحمد عبد الحميد الرازي"))
        self.lineEdit_Nationality.setStatusTip(_translate("MainWindow", "        الجنسية. بالحروف العربية فقط.        مثلا: باكستاني"))
        self.pushButton_addData.setStatusTip(_translate("MainWindow", "إضافة الطالب إلى قائمة البيانات"))
        self.pushButton_addData.setText(_translate("MainWindow", "إضافة"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "الاسم"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "الجنسية"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "رقم الطالب"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "جهة التعليم"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "السكن"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "الجوال"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "الواتس"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "الإعاقة"))
        self.label_Disability.setText(_translate("MainWindow", "الإعاقة:"))
        self.label_Whats.setText(_translate("MainWindow", "الواتس:"))
        self.lineEdit_Disability.setStatusTip(_translate("MainWindow", "        نوع الإعاقة. بالحروف العربية فقط.        مثلا: حركي"))
        self.label_Address.setText(_translate("MainWindow", "السكن:"))
        self.label_Nationality.setText(_translate("MainWindow", "الجنسية:"))
        self.pushButton_displayData.setStatusTip(_translate("MainWindow", "عرض جميع الطلاب و بياناتهم"))
        self.pushButton_displayData.setText(_translate("MainWindow", "عرض"))
        self.label_Mobile.setText(_translate("MainWindow", "الجوال:"))
        self.pushButton_folder_stud.setStatusTip(_translate("MainWindow", "فتح مجلد مع ملف قائمة البيانات"))
        self.pushButton_folder_stud.setText(_translate("MainWindow", "مجلد"))
        self.pushButton_manual_tab1.setStatusTip(_translate("MainWindow", "دليل استعمال البرنامج"))
        self.pushButton_manual_tab1.setText(_translate("MainWindow", "دليل"))
        self.label_FName_2.setText(_translate("MainWindow", "الاسم:"))
        self.pushButton_copy.setStatusTip(_translate("MainWindow", "نسخ البيانات"))
        self.pushButton_copy.setText(_translate("MainWindow", "نسخ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", " التسجيل و البيانات "))
        self.groupBox_2.setTitle(_translate("MainWindow", "  الزيارات و التقارير  "))
        self.textEdit_need.setStatusTip(_translate("MainWindow", "        تكتب الحاجة أو الاقتراح.        مثلا: يحتاج إلى انتقال إلى الوحدة الأولى."))
        self.textEdit_need.setPlaceholderText(_translate("MainWindow", "يرجى كتابة وفقا للنموذج. مثلا: يحتاج إلى (ثم تذكر الحاجة) أو نحو هذا"))
        self.pushButton_saveReport.setStatusTip(_translate("MainWindow", "إنشاء الملف لرفعه إلى المشرف"))
        self.pushButton_saveReport.setText(_translate("MainWindow", "إنشاء التقرير"))
        self.pushButton_updateComboBox.setStatusTip(_translate("MainWindow", "تحديث القائمة"))
        self.pushButton_updateComboBox.setText(_translate("MainWindow", "تحديث"))
        self.pushButton_saveVisit.setStatusTip(_translate("MainWindow", "حفظ نتيجة الزيارة"))
        self.pushButton_saveVisit.setText(_translate("MainWindow", "حفظ"))
        self.label_chooceStud.setText(_translate("MainWindow", "اختر الطالب:"))
        self.label_descriptionChoice.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KacstBook\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#62605d;\">يرجى كتابة رقم الوحدة السكنية و ضغط على &quot;تحديث&quot; ثم اختار اسم الطالب من صندوق التحرير</span></p></body></html>"))
        self.label_resultVisit.setText(_translate("MainWindow", "نتيجة زيارة الطالب:"))
        self.label_descriptionResult.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KacstBook\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" dir=\'rtl\' style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#62605d;\">في حال وجود حاجة أو اقتراح يرجى ضغط على &quot;حفظ&quot; لتحفظ النتيجة في النظام و ينشأ الملف لإرساله إلى المسؤول</span></p></body></html>"))
        self.label_dateVisitReport.setText(_translate("MainWindow", "تقرير الزيارة بالتاريخ:"))
        self.label_descriptionReport.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'KacstBook\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" dir=\'rtl\' style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#62605d;\">يرجى اختيار التاريخ و ضغط على &quot;إنشاء التقرير&quot; لإرساله إلى المسؤول</span></p></body></html>"))
        self.dateEdit.setStatusTip(_translate("MainWindow", "اختر تاريخ الزيارة"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.radioButton_attendance.setText(_translate("MainWindow", "الطالب غائب"))
        self.radioButton_notNead.setText(_translate("MainWindow", "الطالب لا يحتاج إلى أي شيء حاليا"))
        self.lineEdit_unit.setStatusTip(_translate("MainWindow", "        رقم الوحدة. باأرقام فقط.        مثلا: 01"))
        self.lineEdit_unit.setPlaceholderText(_translate("MainWindow", "09"))
        self.label_chooceUnit.setText(_translate("MainWindow", "اكتب رقم الوحدة:"))
        self.pushButton_folder_request.setStatusTip(_translate("MainWindow", "فتح مجلد مع خطابات الطلاب"))
        self.pushButton_folder_request.setText(_translate("MainWindow", "مجلد"))
        self.pushButton_folder_visit.setStatusTip(_translate("MainWindow", "فتح مجلد مع تقارير الزيارة"))
        self.pushButton_folder_visit.setText(_translate("MainWindow", "مجلد"))
        self.pushButton_add_names_firebase.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt; color: red \" >تأكد من اتصال بالنت</span></p></body></html>"))
        self.pushButton_add_names_firebase.setStatusTip(_translate("MainWindow", "إضافة بيانات الطلاب إلى التطبيق"))
        self.pushButton_download_result_firebase.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt; color: red \" >تأكد من اتصال بالنت</span></p></body></html>"))
        self.pushButton_download_result_firebase.setStatusTip(_translate("MainWindow", "تحميل نتائج الزيارة من التطبيق"))
        self.pushButton_manual_tab2.setStatusTip(_translate("MainWindow", "دليل استعمال البرنامج"))
        self.pushButton_manual_tab2.setText(_translate("MainWindow", "دليل"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", " الزيارات و التقارير "))
        self.pushButton_quit.setStatusTip(_translate("MainWindow", "خروج من النظام"))
        self.pushButton_quit.setText(_translate("MainWindow", "خروج"))
        self.pushButton_manual.setStatusTip(_translate("MainWindow", "دليل استعمال البرنامج"))
        self.pushButton_manual.setText(_translate("MainWindow", "دليل"))
